app: fullstack
component: express@1.0.8
name: fullstack-api

inputs:
  src: ./
  roleName: ${output:fullstack-permissions.name}
  # domain: api.${env:domain} Uncomment this when you want to use a custom domain
  env:
    db: ${output:fullstack-db.name}
    dbIndex1: ${output:fullstack-db.indexes.gsi1.name}
    tokenSecret: ${env:tokenSecret}